Build action, Mac & Windows

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -7,23 +7,51 @@ env:
 
 on:
   push:
-    branches: [ "main", "BuildActions" ]
+    branches:
+#      - main
+      - BuildActions
   pull_request:
-    branches: [ "main" ]
+    branches:
+      - main
 
 jobs:
-  build-core:
-    name: Build Core
-    strategy:
-      matrix:
-        os: [ubuntu-latest]
-    runs-on: ${{ matrix.os }}
+  vendor:
+    name: "⚙️ Rust Vendoring ⚙️"
+    runs-on: ubuntu-latest
     outputs:
       output1: ${{ steps.target-dir.outputs.artifact-id }}
     steps:
       - uses: actions/checkout@v3
 
-      - name: Build Cache
+      - name: "Cache"
+        id: cached-build
+        uses: actions/cache@v3
+        continue-on-error: false
+        with:
+          path: |
+            ~/vendor/
+            ~/.cargo/config.toml
+          key: rust-vendor
+          lookup-only: true
+
+      - name: "Vendor"
+        if: ${{ steps.cached-build.outputs.cache-hit != 'true' }}
+        run: |
+          cargo vendor --verbose
+          mv vendor ~
+          cp vendor.toml ~/.cargo/config.toml
+
+
+  build-core:
+    name: "⚙️ Rust Library ⚙️"
+    needs: vendor
+    runs-on: ubuntu-latest
+    outputs:
+      output1: ${{ steps.target-dir.outputs.artifact-id }}
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: "Cache"
         id: cached-build
         uses: actions/cache@v3
         continue-on-error: false
@@ -32,64 +60,169 @@ jobs:
             target/
             ~/vendor/
             ~/.cargo/config.toml
-          key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
+          key: rust-${{ matrix.system.os }}-${{ matrix.system.target }}-${{ hashFiles('Cargo.toml', 'src/visualacuity/**') }}
+          restore-keys: rust-vendor
+          lookup-only: true
 
-      - if: ${{ steps.cached-build.outputs.cache-hit != 'true' }}
-        name: Vendor
-        run: |
-          cargo vendor --verbose
-          mv vendor ~
-          cp vendor.toml ~/.cargo/config.toml
+      - name: "Build"
+        if: ${{ steps.cached-build.outputs.cache-hit != 'true' }}
+        run: cargo build --verbose --package visualacuity
 
-      - if: ${{ steps.cached-build.outputs.cache-hit != 'true' }}
-        name: Build
-        run: cargo build --verbose --workspace
-
-      - if: ${{ steps.cached-build.outputs.cache-hit != 'true' }}
-        name: Test (Rust)
-        run: cargo test --verbose
+      - name: "Test"
+        if: ${{ steps.cached-build.outputs.cache-hit != 'true' }}
+        run: cargo test --verbose --package visualacuity
 
   build-python:
-    needs: build-core
+    name: "🐍 Python Wheel 🐍"
+    needs: vendor
     strategy:
       matrix:
-        os: [ubuntu-latest]
-        python-version: [ "3.9" ]
-    runs-on: ${{ matrix.os }}
+        system:
+          - { os: ubuntu-latest, target: x86_64, architecture: x64 }
+          #          - { os: ubuntu-latest, target: x86, architecture: x86 }
+          #          - { os: ubuntu-latest, target: aarch64, architecture: arm64 }
+          #          - { os: ubuntu-latest, target: armv7, architecture: x64 }
+          #          - { os: ubuntu-latest, target: s390x, architecture: x64 }
+          #          - { os: ubuntu-latest, target: ppc64le, architecture: x64 }
+          - { os: windows-latest, target: x64, architecture: x64 }
+          #          - { os: windows-latest, target: x86, architecture: x86 }
+          - { os: macos-latest, target: x86_64, architecture: x64 }
+          - { os: macos-latest, target: aarch64, architecture: arm64 }
+        python-version:
+          - "3.11"
+    runs-on: ${{ matrix.system.os }}
     steps:
       - uses: actions/checkout@v3
 
-      - name: Build Cache
+      - name: "Cache"
         uses: actions/cache@v3
         continue-on-error: false
         with:
           path: |
-            target/
             ~/vendor/
             ~/.cargo/config.toml
-          key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
+          key: rust-vendor
 
-      - name: Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v3
+      - name: "Set up Python ${{ matrix.python-version }}_${{ matrix.system.architecture}}"
+        uses: actions/setup-python@v4
+        with:
+          python-version: ${{ matrix.python-version }}
+          architecture: ${{ matrix.system.architecture }}
+
+      - name: "Install Python Build Dependencies"
+        run: pip install -r ${{ env.VA_SRC_PYTHON }}/requirements.txt
+
+      - name: "Build sdist"
+        if: matrix.system.os == 'ubuntu-latest' && matrix.system.target == 'x86_64'
+        run: maturin sdist --out dist --manifest-path src/visualacuity-python/Cargo.toml
+
+      - name: "Build wheel"
+        uses: PyO3/maturin-action@v1
+        with:
+          target: ${{ matrix.system.target }}
+          args: --release --out dist --manifest-path ${{ env.VA_SRC_PYTHON }}/Cargo.toml
+          sccache: 'true'
+          manylinux: auto
+
+      - name: "Upload"
+        uses: actions/upload-artifact@v3
+        with:
+          name: python-wheels
+          path: dist
+
+
+  test-python:
+    name: "🐍 Python Tests 🐍"
+    needs: build-python
+    strategy:
+      matrix:
+        os:
+          - ubuntu-latest
+          - windows-latest
+          - macos-latest
+        python-version:
+          - "3.7"
+          - "3.8"
+          - "3.9"
+          - "3.10"
+          - "3.11"
+    runs-on: ${{ matrix.os }}
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: "Set up Python ${{ matrix.python-version }}"
+        uses: actions/setup-python@v4
         with:
           python-version: ${{ matrix.python-version }}
 
-      - name: Install Python Build Dependencies
-        run: pip install -r $VA_SRC_PYTHON/requirements.txt
+      - name: "Download wheel"
+        uses: actions/download-artifact@v3
+        with:
+          name: python-wheels
+          path: dist
 
-      - name: Build Python
+      - name: "Install wheel"
+        run: pip install visualacuity-preview --find-links dist --force-reinstall
+
+      - name: "Test with pytest"
         run: |
-          python -m maturin sdist --manifest-path $VA_SRC_PYTHON/Cargo.toml
-          python -m maturin build --manifest-path $VA_SRC_PYTHON/Cargo.toml
+          pip install pytest pytest-subtests pytest-cov
+          mv src/visualacuity-python/tests .
+          pytest tests --doctest-modules --junitxml=reports/python-test-report.xml # --cov=com --cov-report=xml --cov-report=html
+  #      - name: "Test Report"
+  #        if: success() || failure()
+  #        uses: dorny/test-reporter@v1
+  #        with:
+  #          name: python-test-report-${{ matrix.python-version }}
+  #          path: reports/python-test-report.xml
+  #          reporter: jest-junit
 
-      - name: 'Upload sdist'
-        uses: actions/upload-artifact@v4
-        with:
-          name: sdist
-          path: target/wheels/*.tar.gz
+  publish-python:
+      name: "🐍 Python Publish 🐍"
+      runs-on: ubuntu-latest
+      needs: test-python
 
-      - name: 'Upload wheel'
-        uses: actions/upload-artifact@v4
-        with:
-          name: wheel-${{ matrix.os }}-python-${{ matrix.python-version }}
-          path: target/wheels/*.whl
+      steps:
+        - uses: actions/checkout@v3
+
+        - name: "Download wheels"
+          uses: actions/download-artifact@v3
+          with:
+            name: python-wheels
+            path: dist
+
+        - name: "Set tag"
+          run:
+            PACKAGE_VERSION=$(echo dist/*.tar.gz | sed -e 's/.*-\(.*\)\.tar\.gz/\1/')
+            git tag python-$(PACKAGE_VERSION)
+
+        - name: "Upload binaries to release"
+          uses: svenstaro/upload-release-action@v2
+          with:
+            repo_token: ${{ secrets.GITHUB_TOKEN }}
+            file: dist/*
+            tag: refs/tags/python-latest # ${{ github.ref }}
+            overwrite: true
+            file_glob: true
+
+#        - name: Publish package
+#          uses: pypa/gh-action-pypi-publish@v1
+#          with:
+#            password: ${{ secrets.PYPI_API_TOKEN }}
+
+#  release:
+#    name: Release
+#    runs-on: ubuntu-latest
+#    if: "startsWith(github.ref, 'refs/tags/')"
+#    needs: [linux, windows, macos, sdist]
+#    steps:
+#      - uses: actions/download-artifact@v3
+#        with:
+#          name: wheels
+#      - name: Publish to PyPI
+#        uses: PyO3/maturin-action@v1
+#        env:
+#          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
+#        with:
+#          command: upload
+#          args: --non-interactive --skip-existing *
